apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: test-env
spec:
  selector:
    app: mysql
  type: NodePort # remove if using ClusterIp
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32002
  # clusterIp: none # uncomment if using ClusterIp
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: test-env
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0.30
          name: mysql
          ports:
            - containerPort: 3306
          env:
            # Use secret in real usage
            - name: MYSQL_USER
              valueFrom: 
                secretKeyRef:
                  name: mysql-secret 
                  key: mysql-root-username
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mysql-secret 
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
         