name: Node project
on: push
jobs: 
  build-node:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
        name: check node version
      - run: npm --version
        name: check NPM version
      - uses: actions/checkout@v2
        name: checkout code
      - run: npm install
        name: install NPM packages
      - run: nodejs.js
        name: run nodejs application     
